<a href="https://colab.research.google.com/github/vadlagayathri/machine-learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

new_arr = np.arange(4,10)
print(new_arr)

[4 5 6 7 8 9]


In [ ]:
#n d array
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)
print(arr_1d[2])

[1 2 3 4 5]
3


In [ ]:
#2 d array
import numpy as np
arr_2d = np.array([[1,2,3,4,5],
                  [6,7,8,9,0],
                  [11,12,13,14,15]])
print(arr_2d)
print(arr_2d[2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]
13


In [ ]:
#Shape of an array
arr_2d = np.array([[1,2,3,4,5],
                  [6,7,8,9,0],
                  [11,12,13,14,15]])
print("Shpe of the array:",arr_2d.shape)

Shpe of the array: (3, 5)


In [ ]:
#DATATYPES IN NUMPY
arr_float = np.array([1.1,2.2,3.3],dtype=np.float32)
print("Datatype type of the array:",arr_float.dtype)

Datatype type of the array: float32


In [ ]:
#creating 3d array
arr_3d = np.zeros([2,2,3])
print(arr_3d)
print(arr_3d.dtype)
print("Size of the array:",arr_3d.size)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
float64
Size of the array: 12


In [ ]:
#creating 4d array
arr_4d = np.ones([2,2,3,4])
print(arr_4d)
print(arr_4d.dtype)
print("Size of the array:",arr_4d.size)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]
float64
Size of the array: 48


In [ ]:
#creating 5d array
arr_5d = np.ones([2,2,3,4,1])
print(arr_5d)
print(arr_5d.dtype)
print("Size of the array:",arr_5d.size)

[[[[[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]]


  [[[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]]]



 [[[[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]]


  [[[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]

   [[1.]
    [1.]
    [1.]
    [1.]]]]]
float64
Size of the array: 48
